server {
    listen 8991;
    server_name 175.178.88.66;

    root /www/sites/xizang-route/index;
    index index.html index.htm;

    access_log /www/sites/xizang-route/log/access.log main;
    error_log /www/sites/xizang-route/log/error.log;

    gzip on;
    gzip_types text/css application/javascript application/json;
    gzip_min_length 256;

    location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md) {
        return 404;
    }

    location ^~ /.well-known/acme-challenge {
        allow all;
        root /usr/share/nginx/html;
    }

    if ($uri ~ "^/\.well-known/.*\.(php|jsp|py|js|css|lua|ts|go|zip|tar\.gz|rar|7z|sql|bak)$") {
        return 403;
    }

    location / {
        try_files $uri $uri/ /index.html =404;
    }

    location ~* \.(css|js|json|svg|png|jpg|jpeg|webp|ico|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }

    # 纯静态站点不要 include proxy，否则容易 502/404
    # include /www/sites/xizang-route/proxy/*.conf;
}
